name: ML Pipeline

on:
  push:
    branches: [ main ]

jobs:

  validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install "dvc[all]"

      - name: Pull data with DVC
        run: dvc pull

      - name: Train model
        run: python train.py

      - name: Upload model info
        uses: actions/upload-artifact@v4
        with:
          name: model_info
          path: model_info.txt

      - name: Upload MLflow data
        uses: actions/upload-artifact@v4
        with:
          name: mlruns
          path: mlruns


  deploy:
    needs: validate
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install mlflow

      - name: Download model info
        uses: actions/download-artifact@v4
        with:
          name: model_info
          path: .

      - name: Download MLflow data
        uses: actions/download-artifact@v4
        with:
          name: mlruns
          path: .

      - name: Debug files (important)
        run: ls -R

      - name: Check threshold
        run: python check_threshold.py

      - name: Mock Docker build
        run: |
          echo "Building Docker image for Run ID: $(cat model_info.txt)"
